services:
  - type: worker
    name: telegram-ai-image-bot
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
